### PR TITLE
36 os specific directory

### LINKED ISSUE #36: dir-name-test.eo:30-34: Remove this nop object. Now this...
The puzzle `18-4a5280bc` from #18 has to be resolved: 

https://github.com/objectionary/eo-files/blob/cd8e61daa52e44a9b6ec0fac2a348c0e1299bc1a/src/test/eo/org/eolang/fs/dir-name-test.eo#L30-L34

The puzzle was created by @rultor on 05-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by includealex**
Closes #36.

### CODE REVIEW

**Comment by includealex** [comment]
@Graur please take a look.

**Review by Graur — APPROVED** [review]
@yegor256 please, have a look

**Comment by includealex** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
