### PR TITLE
fixed fail on Windows

### PR DESCRIPTION
**Pull request by Graur**
Closes: #18

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 Please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 I have no idea why `eo-math` is mentioned here

**Comment by Graur** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 Can you run this merge again, please ?

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 I believe it should work, now! Please, make this merge one more time

**Comment by Graur** [comment]
@yegor256 Thanks!

**Pull request merged**
